language: node_js

node_js:
  - "node"
  - "lts/*"
  - "9"
  - "8"

services:
  - mongodb

install:
  - "npm install"

script:
  - "npm run tsc && npm test"

after_success:
  - npm install coveralls@~3.0.0 --global
  - npm run report-coverage