language: node_js

node_js:
  - "node"
  - "lts/*"
  - "9"
  - "8"

services:
  - mongodb

install:
  - "npm install"
  - "npm run lint"

script:
  - "npm run tsc && npm test"

jobs:
  include:
    - stage: Coverage Report
      node_js: node
      after_success:
      - npm install coveralls@~3.0.0 --global
      - npm run report-coverage
